$(document).ready(function() {
  $('input[type=text]').focus()

  var c = new AutocompleteItems([

      // states
      { name: 'alabama', abbreviation: 'al', kind: 'state', token: '#'},
      { name: 'alaska', abbreviation: 'ak', kind: 'state', token: '#'},
      { name: 'american samoa', abbreviation: 'as', kind: 'state', token: '#'},
      { name: 'arizona', abbreviation: 'az', kind: 'state', token: '#'},
      { name: 'arkansas', abbreviation: 'ar', kind: 'state', token: '#'},
      { name: 'california', abbreviation: 'ca', kind: 'state', token: '#'},
      { name: 'colorado', abbreviation: 'co', kind: 'state', token: '#'},
      { name: 'connecticut', abbreviation: 'ct', kind: 'state', token: '#'},
      { name: 'delaware', abbreviation: 'de', kind: 'state', token: '#'},
      { name: 'district of columbia', abbreviation: 'dc', kind: 'state', token: '#'},
      { name: 'federated states of micronesia', abbreviation: 'fm', kind: 'state', token: '#'},
      { name: 'florida', abbreviation: 'fl', kind: 'state', token: '#'},
      { name: 'georgia', abbreviation: 'ga', kind: 'state', token: '#'},
      { name: 'guam', abbreviation: 'gu', kind: 'state', token: '#'},
      { name: 'hawaii', abbreviation: 'hi', kind: 'state', token: '#'},
      { name: 'idaho', abbreviation: 'id', kind: 'state', token: '#'},
      { name: 'illinois', abbreviation: 'il', kind: 'state', token: '#'},
      { name: 'indiana', abbreviation: 'in', kind: 'state', token: '#'},
      { name: 'iowa', abbreviation: 'ia', kind: 'state', token: '#'},
      { name: 'kansas', abbreviation: 'ks', kind: 'state', token: '#'},
      { name: 'kentucky', abbreviation: 'ky', kind: 'state', token: '#'},
      { name: 'louisiana', abbreviation: 'la', kind: 'state', token: '#'},
      { name: 'maine', abbreviation: 'me', kind: 'state', token: '#'},
      { name: 'marshall islands', abbreviation: 'mh', kind: 'state', token: '#'},
      { name: 'maryland', abbreviation: 'md', kind: 'state', token: '#'},
      { name: 'massachusetts', abbreviation: 'ma', kind: 'state', token: '#'},
      { name: 'michigan', abbreviation: 'mi', kind: 'state', token: '#'},
      { name: 'minnesota', abbreviation: 'mn', kind: 'state', token: '#'},
      { name: 'mississippi', abbreviation: 'ms', kind: 'state', token: '#'},
      { name: 'missouri', abbreviation: 'mo', kind: 'state', token: '#'},
      { name: 'montana', abbreviation: 'mt', kind: 'state', token: '#'},
      { name: 'nebraska', abbreviation: 'ne', kind: 'state', token: '#'},
      { name: 'nevada', abbreviation: 'nv', kind: 'state', token: '#'},
      { name: 'new hampshire', abbreviation: 'nh', kind: 'state', token: '#'},
      { name: 'new jersey', abbreviation: 'nj', kind: 'state', token: '#'},
      { name: 'new mexico', abbreviation: 'nm', kind: 'state', token: '#'},
      { name: 'new york', abbreviation: 'ny', kind: 'state', token: '#'},
      { name: 'north carolina', abbreviation: 'nc', kind: 'state', token: '#'},
      { name: 'north dakota', abbreviation: 'nd', kind: 'state', token: '#'},
      { name: 'northern mariana islands', abbreviation: 'mp', kind: 'state', token: '#'},
      { name: 'ohio', abbreviation: 'oh', kind: 'state', token: '#'},
      { name: 'oklahoma', abbreviation: 'ok', kind: 'state', token: '#'},
      { name: 'oregon', abbreviation: 'or', kind: 'state', token: '#'},
      { name: 'palau', abbreviation: 'pw', kind: 'state', token: '#'},
      { name: 'pennsylvania', abbreviation: 'pa', kind: 'state', token: '#'},
      { name: 'puerto rico', abbreviation: 'pr', kind: 'state', token: '#'},
      { name: 'rhode island', abbreviation: 'ri', kind: 'state', token: '#'},
      { name: 'south carolina', abbreviation: 'sc', kind: 'state', token: '#'},
      { name: 'south dakota', abbreviation: 'sd', kind: 'state', token: '#'},
      { name: 'tennessee', abbreviation: 'tn', kind: 'state', token: '#'},
      { name: 'texas', abbreviation: 'tx', kind: 'state', token: '#'},
      { name: 'utah', abbreviation: 'ut', kind: 'state', token: '#'},
      { name: 'vermont', abbreviation: 'vt', kind: 'state', token: '#'},
      { name: 'virgin islands', abbreviation: 'vi', kind: 'state', token: '#'},
      { name: 'virginia', abbreviation: 'va', kind: 'state', token: '#'},
      { name: 'washington', abbreviation: 'wa', kind: 'state', token: '#'},
      { name: 'west virginia', abbreviation: 'wv', kind: 'state', token: '#'},
      { name: 'wisconsin', abbreviation: 'wi', kind: 'state', token: '#'},
      { name: 'wyoming', abbreviation: 'wy', kind: 'state' , token: '#'},

      // countries
      { "name": "bangladesh", "abbreviation": "bd", "kind": "country", token: '[]' },
      { "name": "belgium", "abbreviation": "be", "kind": "country", token: '[]' },
      { "name": "burkina faso", "abbreviation": "bf", "kind": "country", token: '[]' },
      { "name": "bulgaria", "abbreviation": "bg", "kind": "country", token: '[]'  },
      { "name": "bosnia and herzegovina", "abbreviation": "ba", "kind": "country", token: '[]'  },
      { "name": "barbados", "abbreviation": "bb", "kind": "country", token: '[]'  },
      { "name": "wallis and futuna", "abbreviation": "wf", "kind": "country", token: '[]'  },
      { "name": "saint bartelemey", "abbreviation": "bl", "kind": "country", token: '[]'  },
      { "name": "bermuda", "abbreviation": "bm", "kind": "country", token: '[]'  },
      { "name": "brunei darussalam", "abbreviation": "bn", "kind": "country", token: '[]'  },
      { "name": "bolivia", "abbreviation": "bo", "kind": "country", token: '[]'  },
      { "name": "bahrain", "abbreviation": "bh", "kind": "country", token: '[]'  },
      { "name": "burundi", "abbreviation": "bi", "kind": "country", token: '[]'  },
      { "name": "benin", "abbreviation": "bj", "kind": "country", token: '[]'  },
      { "name": "bhutan", "abbreviation": "bt", "kind": "country", token: '[]'  },
      { "name": "jamaica", "abbreviation": "jm", "kind": "country", token: '[]'  },
      { "name": "bouvet island", "abbreviation": "bv", "kind": "country", token: '[]'  },
      { "name": "botswana", "abbreviation": "bw", "kind": "country", token: '[]'  },
      { "name": "samoa", "abbreviation": "ws", "kind": "country", token: '[]'  },
      { "name": "brazil", "abbreviation": "br", "kind": "country", token: '[]'  },
      { "name": "bahamas", "abbreviation": "bs", "kind": "country", token: '[]'  },
      { "name": "jersey", "abbreviation": "je", "kind": "country", token: '[]'  },
      { "name": "belarus", "abbreviation": "by", "kind": "country", token: '[]'  },
      { "name": "other country", "abbreviation": "o1", "kind": "country", token: '[]'  },
      { "name": "latvia", "abbreviation": "lv", "kind": "country", token: '[]'  },
      { "name": "rwanda", "abbreviation": "rw", "kind": "country", token: '[]'  },
      { "name": "serbia", "abbreviation": "rs", "kind": "country", token: '[]'  },
      { "name": "timor-leste", "abbreviation": "tl", "kind": "country", token: '[]'  },
      { "name": "reunion", "abbreviation": "re", "kind": "country", token: '[]'  },
      { "name": "luxembourg", "abbreviation": "lu", "kind": "country", token: '[]'  },
      { "name": "tajikistan", "abbreviation": "tj", "kind": "country", token: '[]'  },
      { "name": "romania", "abbreviation": "ro", "kind": "country", token: '[]'  },
      { "name": "papua new guinea", "abbreviation": "pg", "kind": "country", token: '[]'  },
      { "name": "guinea-bissau", "abbreviation": "gw", "kind": "country", token: '[]'  },
      { "name": "guam", "abbreviation": "gu", "kind": "country", token: '[]'  },
      { "name": "guatemala", "abbreviation": "gt", "kind": "country", token: '[]'  },
      { "name": "south georgia and the south sandwich islands", "abbreviation": "gs", "kind": "country", token: '[]'  },
      { "name": "greece", "abbreviation": "gr", "kind": "country", token: '[]'  },
      { "name": "equatorial guinea", "abbreviation": "gq", "kind": "country", token: '[]'  },
      { "name": "guadeloupe", "abbreviation": "gp", "kind": "country", token: '[]'  },
      { "name": "japan", "abbreviation": "jp", "kind": "country", token: '[]'  },
      { "name": "guyana", "abbreviation": "gy", "kind": "country", token: '[]'  },
      { "name": "guernsey", "abbreviation": "gg", "kind": "country", token: '[]'  },
      { "name": "french guiana", "abbreviation": "gf", "kind": "country", token: '[]'  },
      { "name": "georgia", "abbreviation": "ge", "kind": "country", token: '[]'  },
      { "name": "grenada", "abbreviation": "gd", "kind": "country", token: '[]'  },
      { "name": "united kingdom", "abbreviation": "gb", "kind": "country", token: '[]'  },
      { "name": "gabon", "abbreviation": "ga", "kind": "country", token: '[]'  },
      { "name": "el salvador", "abbreviation": "sv", "kind": "country", token: '[]'  },
      { "name": "guinea", "abbreviation": "gn", "kind": "country", token: '[]'  },
      { "name": "gambia", "abbreviation": "gm", "kind": "country", token: '[]'  },
      { "name": "greenland", "abbreviation": "gl", "kind": "country", token: '[]'  },
      { "name": "gibraltar", "abbreviation": "gi", "kind": "country", token: '[]'  },
      { "name": "ghana", "abbreviation": "gh", "kind": "country", token: '[]'  },
      { "name": "oman", "abbreviation": "om", "kind": "country", token: '[]'  },
      { "name": "tunisia", "abbreviation": "tn", "kind": "country", token: '[]'  },
      { "name": "jordan", "abbreviation": "jo", "kind": "country", token: '[]'  },
      { "name": "croatia", "abbreviation": "hr", "kind": "country", token: '[]'  },
      { "name": "haiti", "abbreviation": "ht", "kind": "country", token: '[]'  },
      { "name": "hungary", "abbreviation": "hu", "kind": "country", token: '[]'  },
      { "name": "hong kong", "abbreviation": "hk", "kind": "country", token: '[]'  },
      { "name": "honduras", "abbreviation": "hn", "kind": "country", token: '[]'  },
      { "name": "heard island and mcdonald islands", "abbreviation": "hm", "kind": "country", token: '[]'  },
      { "name": "venezuela", "abbreviation": "ve", "kind": "country", token: '[]'  },
      { "name": "puerto rico", "abbreviation": "pr", "kind": "country", token: '[]'  },
      { "name": "palestinian territory", "abbreviation": "ps", "kind": "country", token: '[]'  },
      { "name": "palau", "abbreviation": "pw", "kind": "country", token: '[]'  },
      { "name": "portugal", "abbreviation": "pt", "kind": "country", token: '[]'  },
      { "name": "svalbard and jan mayen", "abbreviation": "sj", "kind": "country", token: '[]'  },
      { "name": "paraguay", "abbreviation": "py", "kind": "country", token: '[]'  },
      { "name": "iraq", "abbreviation": "iq", "kind": "country", token: '[]'  },
      { "name": "panama", "abbreviation": "pa", "kind": "country", token: '[]'  },
      { "name": "french polynesia", "abbreviation": "pf", "kind": "country", token: '[]'  },
      { "name": "belize", "abbreviation": "bz", "kind": "country", token: '[]'  },
      { "name": "peru", "abbreviation": "pe", "kind": "country", token: '[]'  },
      { "name": "pakistan", "abbreviation": "pk", "kind": "country", token: '[]'  },
      { "name": "philippines", "abbreviation": "ph", "kind": "country", token: '[]'  },
      { "name": "pitcairn", "abbreviation": "pn", "kind": "country", token: '[]'  },
      { "name": "turkmenistan", "abbreviation": "tm", "kind": "country", token: '[]'  },
      { "name": "poland", "abbreviation": "pl", "kind": "country", token: '[]'  },
      { "name": "saint pierre and miquelon", "abbreviation": "pm", "kind": "country", token: '[]'  },
      { "name": "zambia", "abbreviation": "zm", "kind": "country", token: '[]'  },
      { "name": "western sahara", "abbreviation": "eh", "kind": "country", token: '[]'  },
      { "name": "russian federation", "abbreviation": "ru", "kind": "country", token: '[]'  },
      { "name": "estonia", "abbreviation": "ee", "kind": "country", token: '[]'  },
      { "name": "egypt", "abbreviation": "eg", "kind": "country", token: '[]'  },
      { "name": "tokelau", "abbreviation": "tk", "kind": "country", token: '[]'  },
      { "name": "south africa", "abbreviation": "za", "kind": "country", token: '[]'  },
      { "name": "ecuador", "abbreviation": "ec", "kind": "country", token: '[]'  },
      { "name": "italy", "abbreviation": "it", "kind": "country", token: '[]'  },
      { "name": "vietnam", "abbreviation": "vn", "kind": "country", token: '[]'  },
      { "name": "solomon islands", "abbreviation": "sb", "kind": "country", token: '[]'  },
      { "name": "europe", "abbreviation": "eu", "kind": "country", token: '[]'  },
      { "name": "ethiopia", "abbreviation": "et", "kind": "country", token: '[]'  },
      { "name": "somalia", "abbreviation": "so", "kind": "country", token: '[]'  },
      { "name": "zimbabwe", "abbreviation": "zw", "kind": "country", token: '[]'  },
      { "name": "saudi arabia", "abbreviation": "sa", "kind": "country", token: '[]'  },
      { "name": "spain", "abbreviation": "es", "kind": "country", token: '[]'  },
      { "name": "eritrea", "abbreviation": "er", "kind": "country", token: '[]'  },
      { "name": "montenegro", "abbreviation": "me", "kind": "country", token: '[]'  },
      { "name": "moldova, republic of", "abbreviation": "md", "kind": "country", token: '[]'  },
      { "name": "madagascar", "abbreviation": "mg", "kind": "country", token: '[]'  },
      { "name": "saint martin", "abbreviation": "mf", "kind": "country", token: '[]'  },
      { "name": "morocco", "abbreviation": "ma", "kind": "country", token: '[]'  },
      { "name": "monaco", "abbreviation": "mc", "kind": "country", token: '[]'  },
      { "name": "uzbekistan", "abbreviation": "uz", "kind": "country", token: '[]'  },
      { "name": "myanmar", "abbreviation": "mm", "kind": "country", token: '[]'  },
      { "name": "mali", "abbreviation": "ml", "kind": "country", token: '[]'  },
      { "name": "macao", "abbreviation": "mo", "kind": "country", token: '[]'  },
      { "name": "mongolia", "abbreviation": "mn", "kind": "country", token: '[]'  },
      { "name": "marshall islands", "abbreviation": "mh", "kind": "country", token: '[]'  },
      { "name": "macedonia", "abbreviation": "mk", "kind": "country", token: '[]'  },
      { "name": "mauritius", "abbreviation": "mu", "kind": "country", token: '[]'  },
      { "name": "malta", "abbreviation": "mt", "kind": "country", token: '[]'  },
      { "name": "malawi", "abbreviation": "mw", "kind": "country", token: '[]'  },
      { "name": "maldives", "abbreviation": "mv", "kind": "country", token: '[]'  },
      { "name": "martinique", "abbreviation": "mq", "kind": "country", token: '[]'  },
      { "name": "northern mariana islands", "abbreviation": "mp", "kind": "country", token: '[]'  },
      { "name": "montserrat", "abbreviation": "ms", "kind": "country", token: '[]'  },
      { "name": "mauritania", "abbreviation": "mr", "kind": "country", token: '[]'  },
      { "name": "isle of man", "abbreviation": "im", "kind": "country", token: '[]'  },
      { "name": "uganda", "abbreviation": "ug", "kind": "country", token: '[]'  },
      { "name": "tanzania, united republic of", "abbreviation": "tz", "kind": "country", token: '[]'  },
      { "name": "malaysia", "abbreviation": "my", "kind": "country", token: '[]' },
      { "name": "mexico", "abbreviation": "mx", "kind": "country", token: '[]' },
      { "name": "israel", "abbreviation": "il", "kind": "country", token: '[]' },
      { "name": "france", "abbreviation": "fr", "kind": "country", token: '[]' },
      { "name": "british indian ocean territory", "abbreviation": "io", "kind": "country", token: '[]' },
      { "name": "france, metropolitan", "abbreviation": "fx", "kind": "country", token: '[]' },
      { "name": "saint helena", "abbreviation": "sh", "kind": "country", token: '[]' },
      { "name": "finland", "abbreviation": "fi", "kind": "country", token: '[]' },
      { "name": "fiji", "abbreviation": "fj", "kind": "country", token: '[]' },
      { "name": "falkland islands (malvinas)", "abbreviation": "fk", "kind": "country", token: '[]' },
      { "name": "micronesia, federated states of", "abbreviation": "fm", "kind": "country", token: '[]' },
      { "name": "faroe islands", "abbreviation": "fo", "kind": "country", token: '[]' },
      { "name": "nicaragua", "abbreviation": "ni", "kind": "country", token: '[]' },
      { "name": "netherlands", "abbreviation": "nl", "kind": "country", token: '[]' },
      { "name": "norway", "abbreviation": "no", "kind": "country", token: '[]' },
      { "name": "namibia", "abbreviation": "na", "kind": "country", token: '[]' },
      { "name": "vanuatu", "abbreviation": "vu", "kind": "country", token: '[]' },
      { "name": "new caledonia", "abbreviation": "nc", "kind": "country", token: '[]' },
      { "name": "niger", "abbreviation": "ne", "kind": "country", token: '[]' },
      { "name": "norfolk island", "abbreviation": "nf", "kind": "country", token: '[]' },
      { "name": "nigeria", "abbreviation": "ng", "kind": "country", token: '[]' },
      { "name": "new zealand", "abbreviation": "nz", "kind": "country", token: '[]' },
      { "name": "nepal", "abbreviation": "np", "kind": "country", token: '[]' },
      { "name": "nauru", "abbreviation": "nr", "kind": "country", token: '[]' },
      { "name": "niue", "abbreviation": "nu", "kind": "country", token: '[]' },
      { "name": "cook islands", "abbreviation": "ck", "kind": "country", token: '[]' },
      { "name": "cote d'ivoire", "abbreviation": "ci", "kind": "country", token: '[]' },
      { "name": "switzerland", "abbreviation": "ch", "kind": "country", token: '[]' },
      { "name": "colombia", "abbreviation": "co", "kind": "country", token: '[]' },
      { "name": "china", "abbreviation": "cn", "kind": "country", token: '[]' },
      { "name": "cameroon", "abbreviation": "cm", "kind": "country", token: '[]' },
      { "name": "chile", "abbreviation": "cl", "kind": "country", token: '[]' },
      { "name": "cocos (keeling) islands", "abbreviation": "cc", "kind": "country", token: '[]' },
      { "name": "canada", "abbreviation": "ca", "kind": "country", token: '[]' },
      { "name": "congo", "abbreviation": "cg", "kind": "country", token: '[]' },
      { "name": "central african republic", "abbreviation": "cf", "kind": "country", token: '[]' },
      { "name": "congo, the democratic republic of the", "abbreviation": "cd", "kind": "country", token: '[]' },
      { "name": "czech republic", "abbreviation": "cz", "kind": "country", token: '[]' },
      { "name": "cyprus", "abbreviation": "cy", "kind": "country", token: '[]' },
      { "name": "christmas island", "abbreviation": "cx", "kind": "country", token: '[]' },
      { "name": "costa rica", "abbreviation": "cr", "kind": "country", token: '[]' },
      { "name": "cape verde", "abbreviation": "cv", "kind": "country", token: '[]' },
      { "name": "cuba", "abbreviation": "cu", "kind": "country", token: '[]' },
      { "name": "swaziland", "abbreviation": "sz", "kind": "country", token: '[]' },
      { "name": "syrian arab republic", "abbreviation": "sy", "kind": "country", token: '[]' },
      { "name": "kyrgyzstan", "abbreviation": "kg", "kind": "country", token: '[]' },
      { "name": "kenya", "abbreviation": "ke", "kind": "country", token: '[]' },
      { "name": "suriname", "abbreviation": "sr", "kind": "country", token: '[]' },
      { "name": "kiribati", "abbreviation": "ki", "kind": "country", token: '[]' },
      { "name": "cambodia", "abbreviation": "kh", "kind": "country", token: '[]' },
      { "name": "saint kitts and nevis", "abbreviation": "kn", "kind": "country", token: '[]' },
      { "name": "comoros", "abbreviation": "km", "kind": "country", token: '[]' },
      { "name": "sao tome and principe", "abbreviation": "st", "kind": "country", token: '[]' },
      { "name": "slovakia", "abbreviation": "sk", "kind": "country", token: '[]' },
      { "name": "korea, republic of", "abbreviation": "kr", "kind": "country", token: '[]' },
      { "name": "slovenia", "abbreviation": "si", "kind": "country", token: '[]' },
      { "name": "korea, democratic people's republic of", "abbreviation": "kp", "kind": "country", token: '[]' },
      { "name": "kuwait", "abbreviation": "kw", "kind": "country", token: '[]' },
      { "name": "senegal", "abbreviation": "sn", "kind": "country", token: '[]' },
      { "name": "san marino", "abbreviation": "sm", "kind": "country", token: '[]' },
      { "name": "sierra leone", "abbreviation": "sl", "kind": "country", token: '[]' },
      { "name": "seychelles", "abbreviation": "sc", "kind": "country", token: '[]' },
      { "name": "kazakhstan", "abbreviation": "kz", "kind": "country", token: '[]' },
      { "name": "cayman islands", "abbreviation": "ky", "kind": "country", token: '[]' },
      { "name": "singapore", "abbreviation": "sg", "kind": "country", token: '[]' },
      { "name": "sweden", "abbreviation": "se", "kind": "country", token: '[]' },
      { "name": "sudan", "abbreviation": "sd", "kind": "country", token: '[]' },
      { "name": "dominican republic", "abbreviation": "do", "kind": "country", token: '[]' },
      { "name": "dominica", "abbreviation": "dm", "kind": "country", token: '[]' },
      { "name": "djibouti", "abbreviation": "dj", "kind": "country", token: '[]' },
      { "name": "denmark", "abbreviation": "dk", "kind": "country", token: '[]' },
      { "name": "virgin islands, british", "abbreviation": "vg", "kind": "country", token: '[]' },
      { "name": "germany", "abbreviation": "de", "kind": "country", token: '[]' },
      { "name": "yemen", "abbreviation": "ye", "kind": "country", token: '[]' },
      { "name": "algeria", "abbreviation": "dz", "kind": "country", token: '[]' },
      { "name": "united states", "abbreviation": "us", "kind": "country", token: '[]' },
      { "name": "uruguay", "abbreviation": "uy", "kind": "country", token: '[]' },
      { "name": "mayotte", "abbreviation": "yt", "kind": "country", token: '[]' },
      { "name": "united states minor outlying islands", "abbreviation": "um", "kind": "country", token: '[]' },
      { "name": "lebanon", "abbreviation": "lb", "kind": "country", token: '[]' },
      { "name": "saint lucia", "abbreviation": "lc", "kind": "country", token: '[]' },
      { "name": "lao people's democratic republic", "abbreviation": "la", "kind": "country", token: '[]' },
      { "name": "tuvalu", "abbreviation": "tv", "kind": "country", token: '[]' },
      { "name": "taiwan", "abbreviation": "tw", "kind": "country", token: '[]' },
      { "name": "trinidad and tobago", "abbreviation": "tt", "kind": "country", token: '[]' },
      { "name": "turkey", "abbreviation": "tr", "kind": "country", token: '[]' },
      { "name": "sri lanka", "abbreviation": "lk", "kind": "country", token: '[]' },
      { "name": "liechtenstein", "abbreviation": "li", "kind": "country", token: '[]' },
      { "name": "anonymous proxy", "abbreviation": "a1", "kind": "country", token: '[]' },
      { "name": "tonga", "abbreviation": "to", "kind": "country", token: '[]' },
      { "name": "lithuania", "abbreviation": "lt", "kind": "country", token: '[]' },
      { "name": "satellite provider", "abbreviation": "a2", "kind": "country", token: '[]' },
      { "name": "liberia", "abbreviation": "lr", "kind": "country", token: '[]' },
      { "name": "lesotho", "abbreviation": "ls", "kind": "country", token: '[]' },
      { "name": "thailand", "abbreviation": "th", "kind": "country", token: '[]' },
      { "name": "french southern territories", "abbreviation": "tf", "kind": "country", token: '[]' },
      { "name": "togo", "abbreviation": "tg", "kind": "country", token: '[]' },
      { "name": "chad", "abbreviation": "td", "kind": "country", token: '[]' },
      { "name": "turks and caicos islands", "abbreviation": "tc", "kind": "country", token: '[]' },
      { "name": "libyan arab jamahiriya", "abbreviation": "ly", "kind": "country", token: '[]' },
      { "name": "holy see (vatican city state)", "abbreviation": "va", "kind": "country", token: '[]' },
      { "name": "saint vincent and the grenadines", "abbreviation": "vc", "kind": "country", token: '[]' },
      { "name": "united arab emirates", "abbreviation": "ae", "kind": "country", token: '[]' },
      { "name": "andorra", "abbreviation": "ad", "kind": "country", token: '[]' },
      { "name": "antigua and barbuda", "abbreviation": "ag", "kind": "country", token: '[]' },
      { "name": "afghanistan", "abbreviation": "af", "kind": "country", token: '[]' },
      { "name": "anguilla", "abbreviation": "ai", "kind": "country", token: '[]' },
      { "name": "virgin islands, u.s.", "abbreviation": "vi", "kind": "country", token: '[]' },
      { "name": "iceland", "abbreviation": "is", "kind": "country", token: '[]' },
      { "name": "iran, islamic republic of", "abbreviation": "ir", "kind": "country", token: '[]' },
      { "name": "armenia", "abbreviation": "am", "kind": "country", token: '[]' },
      { "name": "albania", "abbreviation": "al", "kind": "country", token: '[]' },
      { "name": "angola", "abbreviation": "ao", "kind": "country", token: '[]' },
      { "name": "netherlands antilles", "abbreviation": "an", "kind": "country", token: '[]' },
      { "name": "antarctica", "abbreviation": "aq", "kind": "country", token: '[]' },
      { "name": "asia/pacific region", "abbreviation": "ap", "kind": "country", token: '[]' },
      { "name": "american samoa", "abbreviation": "as", "kind": "country", token: '[]' },
      { "name": "argentina", "abbreviation": "ar", "kind": "country", token: '[]' },
      { "name": "australia", "abbreviation": "au", "kind": "country", token: '[]' },
      { "name": "austria", "abbreviation": "at", "kind": "country", token: '[]' },
      { "name": "aruba", "abbreviation": "aw", "kind": "country", token: '[]' },
      { "name": "india", "abbreviation": "in", "kind": "country", token: '[]' },
      { "name": "aland islands", "abbreviation": "ax", "kind": "country", token: '[]' },
      { "name": "azerbaijan", "abbreviation": "az", "kind": "country", token: '[]' },
      { "name": "ireland", "abbreviation": "ie", "kind": "country", token: '[]' },
      { "name": "indonesia", "abbreviation": "id", "kind": "country", token: '[]' },
      { "name": "ukraine", "abbreviation": "ua", "kind": "country", token: '[]' },
      { "name": "qatar", "abbreviation": "qa", "kind": "country", token: '[]' },
      { "name": "mozambique", "abbreviation": "mz", "kind": "country", token: '[]' },

      // special characters
      { name: '"double'       , kind: 'weird'     , token: '!' } ,
      { name: '"another"'     , kind: 'weird'     , token: '!' } ,
      { name: "'single"       , kind: 'weird'     , token: '!' } ,
      { name: "'another'"     , kind: 'weird'     , token: '!' } ,
      { name: "(O_o)"         , kind: 'weird'     , token: '!' } ,
      { name: "{O_o}"         , kind: 'weird'     , token: '!' } ,
      { name: "[O_o]"         , kind: 'weird'     , token: '!' } ,
      { name: "$$$"           , kind: 'weird'     , token: '!' } ,
      { name: "^_^"           , kind: 'weird'     , token: '!' } ,
      { name: "with.a.dot"    , kind: 'weird'     , token: '!' } ,
      { name: "*"             , kind: 'weird'     , token: '!' } ,
      { name: "?questions?"   , kind: 'weird'     , token: '!' } ,

      // without options
      { name: 'one'   },
      { name: 'two'   },
      { name: 'three' }
  ]);

  var v = window.v = new AutocompleteItemsView({
    el: $('.autocomplete'),
    collection: c
  });
});
